//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetDev.Control
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class controleEntities : DbContext
    {
        public controleEntities()
            : base("name=controleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ItemVenda> Itens { get; set; }
        public DbSet<Produto> Produto { get; set; }
        public DbSet<Situacao> Situacao { get; set; }
        public DbSet<Venda> Venda { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<FormaPagamento> FormaPagamento { get; set; }
        public DbSet<Fornecedor> Fornecedor { get; set; }
        public DbSet<Pagamentos> Pagamentos { get; set; }
        public DbSet<SituacaoPagamento> SituacaoPagamento { get; set; }
        public DbSet<Responsavel> Responsavel { get; set; }
        public DbSet<Tarefa> Tarefa { get; set; }
        public DbSet<Arquivo> Arquivo { get; set; }
    }
}
