//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetDev.Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            this.Itens = new HashSet<ItemVenda>();
        }
    
        public int Codigo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<ItemVenda> Itens { get; set; }
    }
}
