//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetDev.Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemVenda
    {
        public ItemVenda()
        {
            this.Arquivo = new HashSet<Arquivo>();
        }
    
        public int Codigo { get; set; }
        public int CodProduto { get; set; }
        public decimal ValorUnit { get; set; }
        public decimal ValorCusto { get; set; }
        public int Quantidade { get; set; }
        public int CodFornecedor { get; set; }
        public int CodSituacao { get; set; }
        public bool FornecedorPago { get; set; }
        public int CodVenda { get; set; }
        public Nullable<System.DateTime> DataPrevisaoEntrega { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Situacao Situacao { get; set; }
        public virtual Venda Venda { get; set; }
        public virtual ICollection<Arquivo> Arquivo { get; set; }
    }
}
