//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetDev.Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamentos
    {
        public int Codigo { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Valor { get; set; }
        public int CodSituacao { get; set; }
        public string Responsavel { get; set; }
        public int CodVenda { get; set; }
    
        public virtual SituacaoPagamento SituacaoPagamento { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
