//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetDev.Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsavel
    {
        public Responsavel()
        {
            this.Tarefa = new HashSet<Tarefa>();
        }
    
        public int CodResponsavel { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Tarefa> Tarefa { get; set; }
    }
}
