//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetDev.Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int CodTarefa { get; set; }
        public string Descrição { get; set; }
        public bool Feito { get; set; }
        public Nullable<System.DateTime> DataFeito { get; set; }
        public Nullable<System.DateTime> DataLimite { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual Responsavel Responsavel { get; set; }
    }
}
