//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetDev.Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public Venda()
        {
            this.Pagamentos = new HashSet<Pagamentos>();
            this.Itens = new HashSet<ItemVenda>();
        }
    
        public int Codigo { get; set; }
        public int CodCliente { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal ValorPago { get; set; }
        public int CodFormaPagamento { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public bool Cancelado { get; set; }
    
        public virtual ICollection<Pagamentos> Pagamentos { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual FormaPagamento FormaPagamento { get; set; }
        public virtual ICollection<ItemVenda> Itens { get; set; }
    }
}
